
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io-docker.pkg.dev/sailor-321711/test-image/test-image:v1', '.' ]


- name: 'asia.gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io-docker.pkg.dev/sailor-321711/test-image/test-image:v1']
options:
  logging: NONE
