
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t','gcr.io/sailor-321711/vi/testing:$COMMIT_SHA','.']
# images:
# - 'gcr.io-docker.pkg.dev/sailor-321711/testimage/testimage:v1'
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'tag', 'react-image', 'gcr.io/sailor-321711/react-image/react-image:v1' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/sailor-321711/vi/testing:$COMMIT_SHA' ]
 

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/sailor-321711/test-image:v1']
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'push', 'gcr.io-docker.pkg.dev/sailor-321711/viswanth-bootlabs/testing:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'testing', '--image','gcr.io/sailor-321711/vi/testing:$COMMIT_SHA']
# images:
# - gcr.io/sailor-321711/github.com/viswanth-bootlabs/testing:$SHORT_SHA
options:
  logging: NONE
