
steps:
- name: 'asia.gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/sailor-321711/react-image/react-image:v1', '.' ]

- name: 'asia.gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/321711/my-v-docker-repo:myimage']
options:
  logging: NONE
