steps:
- name: 'asia.gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/321711/my-v-docker-repo/myimage', '.' ]
- name: 'asia.gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/321711/my-v-docker-repo/myimage']
options:
 logging: NONE
 

